In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('lending_club_ml.csv')
df.drop(['id'], inplace=True, axis=1)

In [4]:
# creating columns for features that had more than 2 outcomes
# I have decided to use subgrade and not grade as these are suppose to be similar features but, subgrade is more granular

df = pd.concat([df, pd.get_dummies(
    df.sub_grade, prefix='sub_grade', drop_first=True)], axis=1)
df = pd.concat([df, pd.get_dummies(df.home_ownership,
                                   prefix='home_ownership', drop_first=True)], axis=1)
df = pd.concat([df, pd.get_dummies(df.verification_status,
                                   prefix='verification_status', drop_first=True)], axis=1)
df = pd.concat(
    [df, pd.get_dummies(df.purpose, prefix='purpose', drop_first=True)], axis=1)
df = pd.concat([df, pd.get_dummies(df.verification_status_joint,
                                   prefix='verification_status_joint', drop_first=True)], axis=1)

df.drop(columns=['sub_grade', 'home_ownership', 'verification_status',
                 'purpose', 'verification_status_joint'], inplace=True)


# conversions for features that only had 2 outcomes

df.disbursement_method = df.disbursement_method.apply(
    lambda disburstment: 1 if disburstment == 'Cash' else 0)

df.application_type = df.application_type.apply(
    lambda app_type: 1 if app_type == 'Individual' else 0)

In [5]:
df_all0 = df.copy()

In [6]:
# if borrower is an indivudal then their secondary features are filled with their single counterpart

sec_list = ['sec_app_fico_range_low', 'sec_app_fico_range_high', 'sec_app_inq_last_6mths', 'sec_app_mort_acc',
            'sec_app_open_acc', 'sec_app_revol_util', 'sec_app_open_act_il','sec_app_num_rev_accts', 'sec_app_chargeoff_within_12_mths',
            'sec_app_collections_12_mths_ex_med', 'sec_app_mths_since_last_major_derog']
joint_list = ['dti_joint', 'revol_bal_joint', 'annual_inc_joint']

for secondary in sec_list:
    df.loc[df.application_type == 1,secondary] = df.loc[df.application_type == 1][secondary[8:]]


for joint in joint_list:
    df.loc[df.application_type == 1,joint] = df.loc[df.application_type == 1][joint[:len(joint)-6]]

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2506738 entries, 0 to 2506737
Columns: 148 entries, loan_amnt to verification_status_joint_Verified
dtypes: float64(89), int64(5), object(1), uint8(53)
memory usage: 1.9+ GB


In [7]:
#fill all nans with 0
df.fillna(0, inplace=True)
df_all0.fillna(0, inplace=True)

In [8]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import average_precision_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score


def scoring(clf, x, y):
    
    #Baseline
    print('Loan passing rate:', np.mean(y))
    print('Balanced loan passing rate:', np.average(y, weights=x['loan_amnt']))
    print('\n')
    
    
    print('score: ', clf.score(x, y))
    # score adjusted for loan amount
    print('balanced_accuracy_score: ', balanced_accuracy_score(
        y, clf.predict(x), sample_weight=x['loan_amnt']))

    print(confusion_matrix(y, clf.predict(x)))
    
    print('F1 score: ', f1_score(y, clf.predict(x)))
    
    print('precision_score: ', precision_score(y, clf.predict(x)))

    # score adjusted for loan amount
    print('average_precision_score: ', average_precision_score(
        y, clf.predict(x), average='weighted', sample_weight=x['loan_amnt']))
    
    print('recall_score: ', recall_score(y, clf.predict(x)))

    print('roc: ', roc_auc_score(y, clf.predict_proba(x)[:, 1]))

    # score adjusted for loan amount
    print('roc_weighted: ', roc_auc_score(y, clf.predict_proba(x)[
          :, 1], average='weighted', sample_weight=x['loan_amnt']))

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X = df.drop(['grade','loan_status'], axis=1)
y = df.loan_status

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

rf_best = RandomForestClassifier(criterion= 'entropy', n_estimators= 101)
rf_best.fit(X_train, y_train)
    
scoring(rf_best, X_test, y_test)

Loan passing rate: 0.8009672589365736
Balanced loan passing rate: 0.7855872316459166


score:  0.9414006505128839
balanced_accuracy_score:  0.8601610947497798
[[108017  41660]
 [  2408 599937]]
F1 score:  0.9645739110022814
precision_score:  0.9350682749451759
average_precision_score:  0.9292143144031701
recall_score:  0.9960022910458293
roc:  0.964646992831969
roc_weighted:  0.9653540974978726


In [10]:
X0 = df_all0.drop(['grade','loan_status'], axis=1)
y0 = df_all0.loan_status

X0_train, X0_test, y0_train, y0_test = train_test_split(X0, y0, test_size=0.3, random_state=42)

rf0_best = RandomForestClassifier(criterion= 'entropy', n_estimators= 101)
rf0_best.fit(X0_train, y0_train)
    
print('RANDOM FOREST')

scoring(rf0_best, X0_test, y0_test)

RANDOM FOREST
Loan passing rate: 0.8009672589365736
Balanced loan passing rate: 0.7855872316459166


score:  0.9413900125262293
balanced_accuracy_score:  0.8598727062980376
[[107973  41704]
 [  2372 599973]]
F1 score:  0.9645697584126326
precision_score:  0.9350077998743916
average_precision_score:  0.9290774560082338
recall_score:  0.9960620574587653
roc:  0.9645527780415752
roc_weighted:  0.9652885481246404


In [11]:
scoring(rf_best, X0_test, y0_test)
scoring(rf0_best, X_test, y_test)

Loan passing rate: 0.8009672589365736
Balanced loan passing rate: 0.7855872316459166


score:  0.827248404966876
balanced_accuracy_score:  0.5811965211185268
[[ 21837 127840]
 [  2073 600272]]
F1 score:  0.902354604470494
precision_score:  0.8244226163007888
average_precision_score:  0.8139324727361922
recall_score:  0.9965584507217624
roc:  0.85017992117754
roc_weighted:  0.8466890413326119
Loan passing rate: 0.8009672589365736
Balanced loan passing rate: 0.7855872316459166


score:  0.9410057152583302
balanced_accuracy_score:  0.8561630060301875
[[106874  42803]
 [  1562 600783]]
F1 score:  0.9643920891285312
precision_score:  0.9334929597598456
average_precision_score:  0.9272818174121961
recall_score:  0.9974068017498278
roc:  0.96258098436719
roc_weighted:  0.9634511096360182
